# Generated by Django 4.2 on 2023-04-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_posts_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='symbol_count',
            field=models.IntegerField(default=0, verbose_name='Symbol count'),
        ),
    ]
